- id: PMID:16815958
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/1533947/bin/pp1411459f09.jpg
  tags:
    - proteins
    - function prediction
- id: PMID:16823370
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fnbt1224/MediaObjects/41587_2006_Article_BFnbt1224_Fig1_HTML.jpg
  tags:
    - proteins
    - function prediction
- id: PMID:17272678
  image: https://raw.githubusercontent.com/doxeylab/doxeylab-website/main/images/m_molbiolevolmsm024f04_4c.jpg
- id: PMID:19014598
- id: PMID:19204814
- id: PMID:20678238
- id: PMID:21976714
- id: PMID:22178248
- id: PMID:23300632
- id: PMID:23715053
- id: PMID:24218641
- id: PMID:25126756
- id: PMID:25399027
- id: PMID:25541486
- id: PMID:26257768
- id: PMID:26541816
- id: PMID:27289211
- id: PMID:27943515
- id: PMID:28052926
- id: PMID:28273103
- id: PMID:28671685
- id: PMID:28761935
- id: PMID:28785417
- id: PMID:28835383
- id: PMID:28900095
- id: PMID:28905000
- id: PMID:29203905
- id: PMID:29205154
- id: PMID:29291746
- id: PMID:29396040
- id: PMID:29438679
- id: PMID:29684130
- id: PMID:29954919
- id: PMID:30058084
- id: PMID:30533733
- id: PMID:30655622
- id: PMID:30733520
- id: PMID:31081040
- id: PMID:31117023
- id: PMID:31240307
- id: PMID:31492962
- id: PMID:31628906
- id: PMID:31646766
- id: PMID:31974369
- id: PMID:31984210
- id: PMID:32124724
- id: PMID:32299893
- id: PMID:32332864
- id: PMID:32345738
- id: PMID:32675206
- id: PMID:32804439
- id: PMID:32902372
- id: PMID:33042865
- id: PMID:33149258
- id: PMID:33326193
- id: PMID:33344628
- id: PMID:33370413
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7853461/bin/ppat.1009181.g002.jpg
  extra-links:
    - type: website
      link: https://diffbase.uwaterloo.ca
  tags:
    - pathogens
    - omics
    - resource

- id: PMID:33384197
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7733689/bin/gr1_lrg.jpg
  tags:
    - COVID-19
- id: PMID:33416870
  image: https://raw.githubusercontent.com/doxeylab/doxeylab-website/main/images/btaa1105f1.jpg
  tags:
    - resource
    - analysis
- id: PMID:33519501
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7838646/bin/fphys-11-588313-g002.jpg
  tags:
    - omics
- id: PMID:33533410
- id: DOI:10.1183/23120541.00705-2020
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7882787/bin/00705-2020.02.jpg
- id: PMID:33852875
  image: https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/15188dcc-880e-40a1-ab18-8dd01ef3b686/fx1.jpg
  tags:
    - omics
    - cancer
- id: PMID:33937724
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8169947/bin/fx1.jpg
  tags:
    - omics
    - COVID-19
- id: PMID:34521345
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8442362/bin/12864_2021_7982_Fig2_HTML.jpg
  tags:
    - pathogens
    - resource
- id: DOI:10.1186/s12931-021-01862-1
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8527633/bin/12931_2021_1862_Fig4_HTML.jpg
- id: PMID:35219763
- id: DOI:10.3389/fmicb.2021.787726
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8865420/bin/fmicb-12-787726-g001.jpg
  tags:
    - analysis
    - toxins



