- id: DOI:10.1038/s41467-023-41174-0
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-023-41174-0/MediaObjects/41467_2023_41174_Fig1_HTML.png
  tags:
    - phylogenomics
    - pathogens
    - evolution
    - toxins
    - ancient DNA

- id: DOI:10.1093/gbe/evad135
  tags:
    - phylogenomics
    - pathogens
    - evolution

- id: DOI:10.1093/gbe/evad129
  tags:
    - machine-learning
    - phylogenomics
    - protein function prediction

- id: DOI:10.3390/v15051116
  image: https://www.mdpi.com/viruses/viruses-15-01116/article_deploy/html/images/viruses-15-01116-g002.png
  tags:
    - phylogenomics
    - viruses

- id: DOI:10.1016/j.heliyon.2023.e13955
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/10018469/bin/gr6.jpg
  tags:
    - phylogenomics
    - pathogens
    - plant-growth promoting bacteria

- id: DOI:10.1183/23120541.00219-2023
  tags:
    - omics
    - lung

- id: DOI:10.1101/2023.07.21.550100
  tags:
    - toxins
    - evolution
    - pathogens

- id: DOI:10.1101/2022.01.20.476458
  tags:
    - COVID-19
    - surveillance
    - pathogens

- id: DOI:10.1038/s41467-022-33964-9
  image: https://media.springernature.com/w290h158/springer-static/image/art%3A10.1038%2Fs41467-022-33964-9/MediaObjects/41467_2022_33964_Fig1_HTML.png
  tags:
    - toxins
    - evolution
    - pathogens

- id: DOI:10.1158/1541-7786.MCR-21-1032
  tags:
    - cancer
    - proteins
    
- id: DOI:10.1016/j.dci.2022.104518
  tags:
    - proteins
    - function prediction
    - pathogens

- id: DOI:10.1101/2022.08.17.504336
  tags:
    - toxins
    - pathogens

- id: DOI:10.1016/j.isci.2022.104614
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2589004222008860-fx1_lrg.jpg
  tags:
    - COVID-19
    - genomics

- id: DOI:10.1038/s42003-022-03333-9
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs42003-022-03333-9/MediaObjects/42003_2022_3333_Fig2_HTML.png
  tags:
    - toxins
    - function prediction
    - evolution
    
- id: PMID:16815958
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/1533947/bin/pp1411459f09.jpg
  tags:
    - proteins
    - function prediction
    
- id: PMID:16823370
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fnbt1224/MediaObjects/41587_2006_Article_BFnbt1224_Fig1_HTML.jpg
  tags:
    - proteins
    - function prediction
- id: PMID:17272678
  image: https://raw.githubusercontent.com/doxeylab/doxeylab-website/main/images/m_molbiolevolmsm024f04_4c.jpg
- id: PMID:19014598
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/2605760/bin/1471-2148-8-316-1.jpg
  tags:
    - toxins
    - analysis
- id: PMID:19204814
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/2614203/bin/ebo-04-139-g02.jpg
- id: PMID:20678238
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/2924342/bin/1472-6807-10-23-4.jpg
  tags:
    - proteins
    - function prediction
- id: PMID:21976714
  image: https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/4b4e72dd-8696-4bfc-99b1-52486f376408/gr9.jpg
  tags:
    - proteins
- id: PMID:22178248
  image: https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/ebf5775a-18f7-40e1-a7e9-d89e30e6df92/fx1.jpg
  tags:
    - proteins
    - analysis
    - computational protein design
    - evolution
- id: PMID:23300632
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/3531485/bin/pone.0052278.g009.jpg
  tags:
    - proteins
    - function prediction
    - evolution
- id: PMID:23715053
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5359739/bin/kvir-04-06-10925180-g002.jpg
  tags:
    - pathogens
    - analysis
- id: PMID:24218641
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/3826502/bin/rstb20130029-g3.jpg
  tags:
    - proteins
    - function prediction
    - analysis
- id: PMID:25126756
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/4303638/bin/ismej2014142f2.jpg
  tags:
    - function prediction
    - microbial ecology
    - omics
- id: PMID:25399027
  image: https://raw.githubusercontent.com/doxeylab/doxeylab-website/main/images/m_btu681f1p.jpg
  tags:
    - resource
    - proteins
    - pathogens
- id: PMID:25541486
  image: https://febs.onlinelibrary.wiley.com/cms/asset/a71329e0-7354-42b1-a8b4-973e9f84e4ce/feb2s0014579314008989-f0015-m.jpg
  tags:
    - toxins
    - function prediction
    - evolution
- id: PMID:26257768
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/4508852/bin/fgene-06-00234-g0003.jpg
  tags:
    - metagenomics
    - proteins
    - function prediction
- id: PMID:26541816
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/4636000/bin/12915_2015_195_Fig2_HTML.jpg
  tags:
    - metagenomics
    - function prediction
    - resource
- id: PMID:27289211
  image: https://raw.githubusercontent.com/doxeylab/doxeylab-website/main/images/cosb.jpg
  tags:
    - function prediction
    - proteins
- id: PMID:27943515
  image: https://raw.githubusercontent.com/doxeylab/doxeylab-website/main/images/emi13643-fig-0005-m.jpg
- id: PMID:28052926
  image: https://raw.githubusercontent.com/doxeylab/doxeylab-website/main/images/pr5d.jpg
- id: PMID:28273103
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5342196/bin/pone.0172545.g004.jpg
  tags:
    - metagenomics
    - proteins
    - function prediction
- id: PMID:28671685
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6556117/bin/nihms-884460-f0006.jpg
  tags:
    - evolution
    - disease
    - omics
- id: PMID:28761935
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5527301/bin/sys0041721210001.jpg
  tags:
    - microbial ecology
    - omics
- id: PMID:28785417
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5537630/bin/mgen-02-80-f003.jpg
  tags:
    - metagenomics
    - microbial ecology
    - toxins
- id: PMID:28835383
  image: https://raw.githubusercontent.com/doxeylab/doxeylab-website/main/images/diosmetin.jpg
  tags:
    - cancer
    - function prediction
- id: PMID:28900095
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5595980/bin/41467_2017_599_Fig1_HTML.jpg
  tags:
    - function prediction
    - proteins
- id: PMID:28905000
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5596199/bin/sys0041721290002.jpg
  tags:
    - omics
    - function prediction
- id: PMID:29203905
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5715007/bin/41598_2017_17236_Fig5_HTML.gif
  tags:
    - evolution
    - function prediction
- id: PMID:29205154
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5716665/bin/elife-29329-fig1.jpg
- id: PMID:29291746
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5748958/bin/40168_2017_383_Fig4_HTML.jpg
  tags:
    - metagenomics
    - microbial ecology
- id: PMID:29396040
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5926203/bin/nihms931834f2.jpg
  tags:
    - toxins
    - pathogens
    - omics
    - function prediction
    - evolution
- id: PMID:29438679
- id: PMID:29684130
- id: PMID:29954919
- id: PMID:30058084
  image: https://raw.githubusercontent.com/doxeylab/doxeylab-website/main/images/dt.png
  tags:
    - pathogens
    - toxins
    - evolution
- id: PMID:30533733
  image: https://raw.githubusercontent.com/doxeylab/doxeylab-website/main/images/contigFasta.jpg
  tags:
    - metagenomics
- id: PMID:30655622
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6336805/bin/41598_2018_36248_Fig1_HTML.jpg
  tags:
    - omics
    - analysis
    - disease
- id: PMID:30733520
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6367388/bin/41598_2018_37647_Fig3_HTML.jpg
  tags:
    - toxins
    - analysis
    - evolution
    - function prediction
- id: PMID:31081040
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6511854/bin/gkz246fig2.jpg
  tags:
    - resource
    - evolution
    - genomics
    - function prediction
- id: PMID:31117023
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6529551/bin/mSystems.00162-19-f0001.jpg
  tags:
    - pathogens
    - toxins
    - evolution
- id: PMID:31240307
  image: https://raw.githubusercontent.com/doxeylab/doxeylab-website/main/images/pygenprop.jpg
  tags:
    - resource
    - genomics
- id: PMID:31492962
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6908642/bin/41396_2019_502_Fig1_HTML.jpg
  tags:
    - metagenomics
    - microbial ecology
- id: PMID:31628906
  image: https://raw.githubusercontent.com/doxeylab/doxeylab-website/main/images/biofilmmodel.jpg
- id: PMID:31646766
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6811686/bin/PHY2-7-e14249-g001.jpg
  tags:
    - transcriptomics
    - lung
- id: PMID:31974369
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6978384/bin/41467_2020_14306_Fig1_HTML.jpg
  tags:
    - toxins
    - pathogens
    - analysis
    - proteins
    - function prediction
- id: PMID:31984210
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6970181/bin/00265-2019.01.jpg
- id: PMID:32124724
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7200070/bin/mgen-6-341-g002.jpg
  tags:
    - analysis
- id: PMID:32299893
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7163031/bin/MRA.01575-19-f0001.jpg
  tags:
    - omics
- id: PMID:32332864
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7305129/bin/41396_2020_650_Fig3_HTML.jpg
  tags:
    - omics
    - microbial ecology
- id: PMID:32345738
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7190384/bin/mSystems.00145-20-f0002.jpg
  tags:
    - omics
    - microbial ecology
    - toxins
- id: DOI:10.1183/13993003.01123-2020
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7366180/bin/ERJ-01123-2020.03.jpg
  tags:
    - COVID-19
    - analysis
- id: PMID:32804439
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7821379/bin/MMI-114-979-g002.jpg
  tags:
    - proteins
    - function prediction
- id: PMID:32902372
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7819352/bin/jgv-101-1251-g001.jpg
  tags:
  -  COVID-19
  -  analysis
- id: PMID:33042865
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7525020/bin/fcimb-10-00487-g0001.jpg
  tags:
    - omics
    - lung
- id: PMID:33149258
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7643111/bin/41598_2020_76010_Fig6_HTML.jpg
  tags:
    - proteins
    - function prediction
    - omics
- id: PMID:33326193
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7291946/bin/baz085f3.jpg
- id: PMID:33344628
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7737429/bin/00128-2020.01.jpg
- id: PMID:33370413
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7853461/bin/ppat.1009181.g002.jpg
  extra-links:
    - type: website
      link: https://diffbase.uwaterloo.ca
  tags:
    - pathogens
    - omics
    - resource

- id: PMID:33384197
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7733689/bin/gr1_lrg.jpg
  tags:
    - COVID-19
- id: PMID:33416870
  image: https://raw.githubusercontent.com/doxeylab/doxeylab-website/main/images/btaa1105f1.jpg
  tags:
    - resource
    - analysis
- id: PMID:33519501
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7838646/bin/fphys-11-588313-g002.jpg
  tags:
    - omics
- id: PMID:33533410
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7931817/bin/giab006fig1.jpg
  tags:
    - resource
    - microbial ecology
    - metagenomics
- id: DOI:10.1183/23120541.00705-2020
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7882787/bin/00705-2020.02.jpg
- id: PMID:33852875
  image: https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/15188dcc-880e-40a1-ab18-8dd01ef3b686/fx1.jpg
  tags:
    - omics
    - cancer
- id: PMID:33937724
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8169947/bin/fx1.jpg
  tags:
    - omics
    - COVID-19
- id: PMID:34521345
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8442362/bin/12864_2021_7982_Fig2_HTML.jpg
  tags:
    - pathogens
    - resource
- id: DOI:10.1186/s12931-021-01862-1
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8527633/bin/12931_2021_1862_Fig4_HTML.jpg
- id: PMID:35219763
  image: https://raw.githubusercontent.com/doxeylab/doxeylab-website/main/images/regtoxpharm.png
- id: DOI:10.3389/fmicb.2021.787726
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8865420/bin/fmicb-12-787726-g001.jpg
  tags:
    - analysis
    - toxins



